"""Add daily wages for per-day and weekly payment

Revision ID: 77bd49d0caae
Revises: 84291eff8405
Create Date: 2026-03-23 00:27:14.150388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bd49d0caae'
down_revision = '84291eff8405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_wages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('per_hour_rate', sa.Float(), nullable=True),
    sa.Column('per_day_rate', sa.Float(), nullable=True),
    sa.Column('pieces_completed', sa.Integer(), nullable=True),
    sa.Column('per_piece_rate', sa.Float(), nullable=True),
    sa.Column('base_pay', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('overtime_rate', sa.Float(), nullable=True),
    sa.Column('overtime_pay', sa.Float(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('deduction', sa.Float(), nullable=True),
    sa.Column('total_pay', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', name='daily_payment_status_enum'), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_wage_user_date')
    )
    with op.batch_alter_table('daily_wages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_wages_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_wages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_wages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_wages_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_wages_payment_status'))

    op.drop_table('daily_wages')
    # ### end Alembic commands ###
