"""Add metal prices and history

Revision ID: 7aa29a0a9814
Revises: 6e51a51fcd77
Create Date: 2026-03-23 16:22:14.180610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa29a0a9814'
down_revision = '6e51a51fcd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metal', sa.String(length=20), nullable=False),
    sa.Column('purity', sa.String(length=20), nullable=True),
    sa.Column('price_per_gram', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal', 'purity', 'date', name='uq_metal_purity_date')
    )
    with op.batch_alter_table('metal_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metal_price_history_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_metal_price_history_metal'), ['metal'], unique=False)

    op.create_table('metal_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metal', sa.String(length=20), nullable=False),
    sa.Column('purity', sa.String(length=20), nullable=True),
    sa.Column('price_per_gram', sa.Float(), nullable=False),
    sa.Column('price_per_10gram', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metal_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metal_prices_metal'), ['metal'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metal_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metal_prices_metal'))

    op.drop_table('metal_prices')
    with op.batch_alter_table('metal_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metal_price_history_metal'))
        batch_op.drop_index(batch_op.f('ix_metal_price_history_date'))

    op.drop_table('metal_price_history')
    # ### end Alembic commands ###
