"""Add attendance and attendance config

Revision ID: 7e9198e4a92c
Revises: 00959f6e28cd
Create Date: 2026-03-22 01:50:11.613775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9198e4a92c'
down_revision = '00959f6e28cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('half_day_threshold_hours', sa.Float(), nullable=True),
    sa.Column('full_day_threshold_hours', sa.Float(), nullable=True),
    sa.Column('overtime_after_hours', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_in_lat', sa.Float(), nullable=True),
    sa.Column('check_in_lng', sa.Float(), nullable=True),
    sa.Column('check_in_address', sa.String(length=500), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_lat', sa.Float(), nullable=True),
    sa.Column('check_out_lng', sa.Float(), nullable=True),
    sa.Column('check_out_address', sa.String(length=500), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'half_day', 'on_leave', 'holiday', 'weekend', name='attendance_status_enum'), nullable=False),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edit_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))

    op.drop_table('attendance')
    op.drop_table('attendance_config')
    # ### end Alembic commands ###
