"""Add payroll - salary structure and payslips

Revision ID: 84291eff8405
Revises: 6fa5be17766f
Create Date: 2026-03-23 00:18:28.953999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84291eff8405'
down_revision = '6fa5be17766f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('hra', sa.Float(), nullable=True),
    sa.Column('da', sa.Float(), nullable=True),
    sa.Column('conveyance', sa.Float(), nullable=True),
    sa.Column('medical_allowance', sa.Float(), nullable=True),
    sa.Column('special_allowance', sa.Float(), nullable=True),
    sa.Column('other_allowance', sa.Float(), nullable=True),
    sa.Column('pf_employee', sa.Float(), nullable=True),
    sa.Column('pf_employer', sa.Float(), nullable=True),
    sa.Column('esi_employee', sa.Float(), nullable=True),
    sa.Column('esi_employer', sa.Float(), nullable=True),
    sa.Column('professional_tax', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('other_deduction', sa.Float(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('ctc', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_structures_user_id'), ['user_id'], unique=False)

    op.create_table('payslips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=True),
    sa.Column('hra', sa.Float(), nullable=True),
    sa.Column('da', sa.Float(), nullable=True),
    sa.Column('conveyance', sa.Float(), nullable=True),
    sa.Column('medical_allowance', sa.Float(), nullable=True),
    sa.Column('special_allowance', sa.Float(), nullable=True),
    sa.Column('other_allowance', sa.Float(), nullable=True),
    sa.Column('pf_employee', sa.Float(), nullable=True),
    sa.Column('esi_employee', sa.Float(), nullable=True),
    sa.Column('professional_tax', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('other_deduction', sa.Float(), nullable=True),
    sa.Column('overtime_pay', sa.Float(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('leave_deduction', sa.Float(), nullable=True),
    sa.Column('late_deduction', sa.Float(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('leave_days', sa.Float(), nullable=True),
    sa.Column('absent_days', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('gross_earnings', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'processed', 'paid', 'failed', name='payment_status_enum'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('payment_notes', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year', name='uq_user_month_year')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_user_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_payment_status'))

    op.drop_table('payslips')
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_structures_user_id'))

    op.drop_table('salary_structures')
    # ### end Alembic commands ###
