"""Add employee profiles, bank details, documents

Revision ID: 856d218117d5
Revises: 
Create Date: 2026-03-22 01:21:29.084316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856d218117d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('account_number_enc', sa.Text(), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('account_holder_name', sa.String(length=100), nullable=True),
    sa.Column('pan_number_enc', sa.Text(), nullable=True),
    sa.Column('uan_number', sa.String(length=30), nullable=True),
    sa.Column('esi_number', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('aadhaar', 'pan', 'passport', 'driving_license', 'voter_id', 'offer_letter', 'experience_letter', 'relieving_letter', 'salary_slip', 'bank_statement', 'photo', 'other', name='doc_type_enum'), nullable=False),
    sa.Column('doc_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_documents_user_id'), ['user_id'], unique=False)

    op.create_table('employee_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', 'widowed', name='marital_enum'), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('perm_address_line1', sa.String(length=255), nullable=True),
    sa.Column('perm_address_line2', sa.String(length=255), nullable=True),
    sa.Column('perm_city', sa.String(length=100), nullable=True),
    sa.Column('perm_state', sa.String(length=100), nullable=True),
    sa.Column('perm_pincode', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('spouse_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_profiles')
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_documents_user_id'))

    op.drop_table('employee_documents')
    op.drop_table('bank_details')
    # ### end Alembic commands ###
