"""payments tables

Revision ID: aac9ab681369
Revises: 2660cce5fa31
Create Date: 2026-04-01 18:28:14.875902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac9ab681369'
down_revision = '2660cce5fa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_payment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wage_type', sa.Enum('MONTHLY_SALARY', 'DAILY_WAGE', 'PER_TASK', name='wage_type_enum'), nullable=False),
    sa.Column('wage_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_payment_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_payment_configs_user_id'), ['user_id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK', 'UPI', name='payment_method_enum'), nullable=False),
    sa.Column('reference_note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'REVERSED', name='payment_status_enum'), nullable=False),
    sa.Column('reversal_of', sa.Integer(), nullable=True),
    sa.Column('reversal_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversal_of'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_employee_id'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('employee_payment_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_payment_configs_user_id'))

    op.drop_table('employee_payment_configs')
    # ### end Alembic commands ###
